### ISSUE TITLE
Скрейпер и скачиватель

### ISSUE THREAD

**Issue by ghost** [aq1/WillBeams#15]
В порядке работы конвейера:
- [ ] парсер списка урлов вебм и прилагающейся инфы (урл превью, md5 и прочее). должен тупо парсить и выдавать всё что напарсил без попыток отсеивания
- [ ] предварительный отсеиватель (не требующий качать вебм). Проверка по урлу-источнику, _по предварительно известным_ md5/размеру файла. Очень желательно это всё делать отдельными моделями, таблицами и не срать полями в Video. Потому что источников может быть много разных (да хоть сами руками добавлять будем), и способы идентификации для каждого источника свои (точнее _набор способов_ для каждого свой, и каждый элемент такого набора нужно делать отдельным модулем с отдельным хранилищем данных, например по паре md5+size, по какому-то хитрому анализу видеоряда, по урлу-источнику, итд; каждый из способов можно будет отключить или добавить новый; каждый из них вяжется через foreignkey/OneToOne к модели Video).
- [ ] скачиватель файлов по урлам, берущий задания с помощью очереди, например rabbitmq, так мы сможем запустить несколько скачивателей на разных машинах и знать что задания не повторятся. парсер+предварительный отсев соответственно насирают данными в эту очередь.
- [ ] анализатор видео (отсеиватель после скачивания). Та же специфика что и для предварительного отсеивателя. Вертеться будет тоже где-то на отдельных серверах, скорее всего вместе со скачивателем чтобы файлы лишний раз туда-сюда не гонять. Процесс скорее всего будет тяжёлый и потребуется мультипроцессинг. Для начала здесь тупо считаем md5 и размер файла, кадры будем анализировать позже.

Вот примерно здесь, если видео ещё не отсеяно, уже точно можно сказать что оно будет добавлено.
- [ ] построитель превью. с возможностью выдать NULL (без превью) и вытянуть сосачевское превью из прилагавшейся к видео инфы. пока что так. Затем добавим чтение кадров и построение своей картинки.
- [ ] забрасыватель видео на сайт (добавление в SQL, перемещение файлов вебм и превью).

Очень круто каждый из шагов сделать отдельным процессом, а не собирать один большой скрейпер делающий всё и сразу. Потому что по факту самого скрейпера (который хтмл и жсон парсит) там будет процентов 10. Rabbitmq очень несложная весь, советую глянуть. На первых пока можно использовать в качестве основного хранилища тот SQL сервер. Но обычно это плохая практика, так как его будет нагружать ещё и сайт.

**Comment by aq1** [comment]
Закрою. Можно читать как источник информации. Задачи разделены.
