### ISSUE TITLE
Scraper: parser

### ISSUE THREAD

**Issue by aq1** [aq1/WillBeams#20]
Получать данные с сайта, мониторить треды и отправлять список webm без какой либо сортировки и проверки.

**Comment by aq1** [comment]
Сделано. Смотри parser.py ветка parser

**Comment by ghost** [comment]
- Нет документации для подключения другим разработчиком.
- Нет подгонки под наш формат сообщений. См. https://github.com/aq1/WillBeams/blob/master/pipeline/downloader.py#L45
- Не собрано внутри pipeline (у нас там есть универсальный код под rabbit)
- Не позволяет добавлять парсеры для других борд. Должно быть как в pipeline, например где md5. Мы просто рядом с md5.py можем добавить ещё один метод рассчёта, таким образом достигается декомпозиция и расширяемость.
- Нет предварительной проверки по md5 вызовом RPC. См. https://github.com/aq1/WillBeams/blob/master/pipeline/downloader.py#L35 https://github.com/aq1/WillBeams/blob/master/pipeline/unicheck/__init__.py#L2
