### ISSUE TITLE
Scraper: downloader

### ISSUE THREAD

**Issue by aq1** [aq1/WillBeams#22]
Берет ссылки из очереди и скачивает файлы, добавляя их в нужную модель.

**Comment by aq1** [comment]
Скажите куда и как сохранять. Я имею в виду модель джанги там или просто на диск..

**Comment by ghost** [comment]
По идее это всё должно срабатывать используя addvideo и наш модуль постройки превью. Сохранять должно в tempfile, вызывать addvideo и удалять.

**Comment by ghost** [comment]
Ага, ну и чтение заданий собственно из rabbitmq. Туда же запросы по вычисленному md5 от файла (это можно просто пока stub сделать, без реализации).
